# Final Exercise on pandas

In the last notebooks you have learned a lot of new things, and you have also been able to practice them. Only by practicing will you become more confident in using the methods and hopefully it will stick in your mind better.
Thus, here is another exercise on pandas, in which you are asked to do a few different things with the new tools we learned about (methods for combining records, `pd.cut` and `pivot tables`).

We'll be working with the `wine` datasets that are located in the `data` folder in this day's directory.

1. Read the `winequality-red.csv` data into a `DataFrame`, and the `winequality-white.csv` into another `DataFrame`.

In [184]:
import pandas as pd
import numpy as np
r_wines = pd.read_csv('data/winequality-red.csv', delimiter = ";")
r_wines.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [185]:
w_wines = pd.read_csv('data/winequality-white.csv', delimiter = ";")
w_wines.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

2. Double check that you've read them in right by using some of the attributes and methods available on `DataFrames` for getting a general sense of your data.

In [186]:
w_wines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [187]:
r_wines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [188]:
#change the column names so that they don't use white spaces
r_wines.columns = [col.replace(" ","_") for col in r_wines.columns]
w_wines.columns = [col.replace (" ","_") for col in w_wines.columns]

3. I've decided that this month I want to stay away from wines with relatively high alcohol content. To do that, I'm going to avoid any wines that have a greater alcohol content than the mean alcohol content, and you're going to help me do this. To achieve this, let's do the following: 

  * Find the mean alcohol content, separately, for reds and whites.  
  * Create a `Series` that holds whether each row in each `DataFrame` (the reds, and whites) has a higher alcohol content than the mean. 
  * Merge this `Series` onto the `DataFrame`. I can imagine doing this with either a `.join()` or using `pd.concat()`. For practice, do it with both. Note: merges with `Series` work the same way that they work with `DataFrames`.  
  * Return back to me all those rows that will help me stay away from those wines with a higher alcohol content.

In [189]:
mean_alc_r = r_wines['alcohol'].mean()
mean_alc_w = w_wines['alcohol'].mean()

In [190]:
#I added the columns directly to the dataframe, no merge necessary
r_wines['alc_above_mean'] = r_wines['alcohol'] > mean_alc_r
w_wines['alc_above_mean'] = w_wines['alcohol'] > mean_alc_r
w_wines.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,alc_above_mean
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,False
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,False
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,False
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,False
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,False

4. Let's say that I want to get started on cutting back next month. This time, though, I want to focus on staying away from those wines with a high acidity. Specifically, I want to stay away from those wines that are in the highest bin of fixed acidity (highest bin out of 5). You're now going to help me do this. To achieve this, let's do the following: 

 * Separate the rows in each `DataFrame` into 5 equal width bins (not equal to quintiles) based off their fixed acidity. 
 * Merge the resulting `Series` holding these 5 bins onto the original `DataFrame`. I can imagine also doing this with either `.join()` or using `pd.concat()`. Try doing it with both for practice. 
 * Return back to me all those rows that are **not in** the top bin in terms of fixed acidity.

In [191]:
print(r_wines['fixed_acidity'].min())
print(r_wines['fixed_acidity'].max())
print(w_wines['fixed_acidity'].min())
print(w_wines['fixed_acidity'].max())

4.6
15.9
3.8
14.2

In [192]:
fixed_acidity_series_r = pd.cut(r_wines['fixed_acidity'], 
                                bins = np.arange(4,17))
fixed_acidity_series_r.name = 'fa_bin_r'
r_wines = pd.concat([r_wines, fixed_acidity_series_r], axis=1)

In [193]:
fixed_acidity_series_w = pd.cut(w_wines['fixed_acidity'], 
                                bins = np.arange(4,17))
fixed_acidity_series_w.name = 'fa_bin_w'
w_wines = pd.concat([w_wines, fixed_acidity_series_w], axis=1)
w_wines.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,alc_above_mean,fa_bin_w
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,False,"(6, 7]"
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,False,"(6, 7]"
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,False,"(8, 9]"
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,False,"(7, 8]"
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,False,"(7, 8]"

5. Let's say that I now want to know how much my decision to avoid those wines with higher `alcohol` content is going to limit the `quality` of wines that I can drink. To figure this out, I want to know a couple of things: 

 * The average `alcohol` content for those reds above the mean `alcohol` level, by quality.
 * The average `alcohol` content for those whites above the mean `alcohol` level, by quality. 
 
 Use a `pivot table` to solve this.

In [204]:
#average alcohol content 
#reds above the mean > mask 
maskred = r_wines['alc_above_mean'] == True
red_subset = r_wines[maskred]
red_subset.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,alc_above_mean,fa_bin_r
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,True,"(7, 8]"
11,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5,True,"(7, 8]"
16,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.9969,3.30,0.75,10.5,7,True,"(8, 9]"
31,6.9,0.685,0.00,2.5,0.105,22.0,37.0,0.9966,3.46,0.57,10.6,6,True,"(6, 7]"
36,7.8,0.600,0.14,2.4,0.086,3.0,15.0,0.9975,3.42,0.60,10.8,6,True,"(7, 8]"

In [206]:
#whites above the mean > mask 
maskwhite = w_wines['alc_above_mean'] == True
white_subset = w_wines[maskwhite]
white_subset.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,alc_above_mean,fa_bin_w
9,8.1,0.22,0.43,1.50,0.044,28.0,129.0,0.9938,3.22,0.45,11.0,6,True,"(8, 9]"
10,8.1,0.27,0.41,1.45,0.033,11.0,63.0,0.9908,2.99,0.56,12.0,5,True,"(8, 9]"
12,7.9,0.18,0.37,1.20,0.040,16.0,75.0,0.9920,3.18,0.63,10.8,5,True,"(7, 8]"
13,6.6,0.16,0.40,1.50,0.044,48.0,143.0,0.9912,3.54,0.52,12.4,7,True,"(6, 7]"
15,6.6,0.17,0.38,1.50,0.032,28.0,112.0,0.9914,3.25,0.55,11.4,7,True,"(6, 7]"

In [209]:
#pivot_table. relevant columns: alcohol, quality 
pd.pivot_table(red_subset, values = 'alcohol',
               index = 'quality')

           alcohol
quality
3        10.866667
4        11.295000
5        11.088686
6        11.437214
7        11.708236
8        12.368750

In [217]:
#pivot_table. relevant columns: alcohol, quality 
pd.pivot_table(white_subset, values = 'alcohol',
               index = 'quality')

           alcohol
quality
3        11.320000
4        11.290909
5        11.120876
6        11.521489
7        11.872989
8        12.094521
9        12.625000

6. Now, do the same for my decision to avoid wines with a high acidity next month: 

 * Find the average `alcohol` content for reds, by `quality` and `fixed acidity` bin. 
 * Find the average `alcohol` content for whites, by `quality` and `fixed acidity` bin. 
 
  Use a `pivot table` to solve this.